### PR TITLE
2.3.2

### PR DESCRIPTION
**Pull request by aristath**

### CODE REVIEW

**Comment by carasmo** [comment]
Will this have the `Kirki_Fonts_Google::$force_load_all_variants = true;` in it? Thanks!

**Comment by aristath** [comment]
> Will this have the Kirki_Fonts_Google::$force_load_all_variants = true; in it? Thanks!

It's already in 2.3.1 :)

**Comment by manuelmoreale** [comment]
Hey @aristath any chance we'll have `postMessage` working for the typography field in the next release? I'm talking about color, font size and that kind of stuff and not the font family ;)

**Comment by guillaumemolter** [comment]
@aristath do you expect to ship 2.3.2 today/tonight?

**Comment by aristath** [comment]
no, I need to fix a couple more things and test things a lot...

**Comment by manuelmoreale** [comment]
@aristath let me know if there's anything I can do to help you test the 2.3.2

**Comment by aristath** [comment]
@manuelmoreale I'll take you up on that offer...

What needs testing right now is the new editor control. So if you can test that I'd be grateful :+1:

**Comment by manuelmoreale** [comment]
Hey @aristath I just downloaded the last dev version and played with the editor a bit.
Everything seems to work just fine.
The new link popup works fine and I also tried using multiple editors and the switch works really well.
It's a bit weird at first but is a neat solution.
One thing we might consider is to add the ability to resize vertically the editor area.

Nice work as usual 👍

**Comment by manuelmoreale** [comment]
@aristath one minor improvement can be automatically close the editor when the user clicks on the back arrow to exit the current section. Just an idea ;)

**Pull request merged**
