### PR TITLE
3.0.10

### PR DESCRIPTION
**Pull request by aristath**

### CODE REVIEW

**Comment by carasmo** [comment]
Hello! ETA on the plugin version be updated with all this goodness?

**Comment by aristath** [comment]
@carasmo I have to refactor the controls resetting and then do some testing.
Rough estimate sometime next week. 👍

**Comment by danielortiz** [comment]
please, would mind  supporting custom controls when designing the control reset refactor?

**Comment by aristath** [comment]
@danielortiz already sort of implemented. ;)

**Comment by aristath** [comment]
@danielortiz in short:
All controls have been rewritten.
Each control now has a couple of extra functions: `kirkiSetValue`, `kirkiSetControlValue`.
The 1st one sets the value in the customize object.
The 2nd one takes care of visually changing the value displayed in the control when needed.
If a control has these 2 methods in them, then they will be called.
But please don't implement them yet because the naming is still quite fluid, I don't think they'll remain with those names or if they will be moved to a larger `kirki` object I'm creating.
But you can see it's already implemented here: https://github.com/aristath/kirki/blob/f00bb73fd483630e58491c8cbeff4f6e3da566ff/modules/reset/reset.js#L17-L27 (though like I said I haven't decided on the names yet)

**Comment by danielortiz** [comment]
Neat :D, nice job you're doing. Thanks for all you did

**Pull request merged**
