### PR TITLE
Fix radio button required

### PR DESCRIPTION
**Pull request by DevelopOnline**

### CODE REVIEW

**Comment by aristath** [comment]
Hey again!

Can you please submit this against the master instead?

Also, why did you remove the conditionals on line 113? https://github.com/aristath/kirki/pull/175/files#diff-0b52923a1cdfd4508362576683d70c6bL113
It looks like you're hard-coding it to check for `is(":checked") )`
However what we're trying to accomplish is make the required work for all control types.
I know it's far for complete though (that's why it doesn't even exist on the documentation site), and thank you for looking into this issue!

**Comment by DevelopOnline** [comment]
Hi there.
I've created a pull request to master branch.

I hard coded line 113 to check for `is(":checked")`, because a radio control item (e.g. with `colorful` value attribute), has it's own value all the time, and if you try to use it as a condition, it always returns true, whether or not it was checked.

**Comment by aristath** [comment]
ok, I can see you're right about radio controls.
It was previously like this:

``` php
$script .= ( 'checkbox' == $type ) ? 'is(":checked") ) {' : 'val() ' . $dependency['operator'] . ' "' . $dependency['value'] . '") {';
```

and now with your commit it looks like this:

``` php
$script .= 'is(":checked") ) {';
```

Your version works well for radios & checkboxes, but it fails when the dependency is for example a select control, an image control or anything else.
So... Could you please do it like this? This should account for all cases:

``` php
$script .= ( 'checkbox' == $type || 'radio' == $type ) ? 'is(":checked") ) {' : 'val() ' . $dependency['operator'] . ' "' . $dependency['value'] . '") {';
```

**Comment by DevelopOnline** [comment]
I think it should be:

```
$script .= ( 'checkbox' == $type || 'radio' == $type || 'radio-buttonset' == $type || 'radio-image' == $type ) ? 'is(":checked") ) {' : 'val() ' . $dependency['operator'] . ' "' . $dependency['value'] . '") {';
```

What is your idea?

**Comment by fovoc** [comment]
https://github.com/aristath/kirki/blob/master/includes/Scripts/Customizer/Required.php#L50-L54

it all comes down to 'select', 'radio' or 'checkbox' so a

`'select' != $type`

should do the trick ;)

**Pull request closed without merging**
