### PR TITLE
New controls, adjustments, modules (oh my!)

### PR DESCRIPTION
**Pull request by CaptJiggly**
Hey Ari.

After several months of adding, modding and testing, I feel its time to actually do a pull request.

There may still be some testing required, BUT I don't want to keep you in the dark too long about what my partner and I have been working on/implementing in our own WP theme.

This framework has been an awesome edition to our theme and we wanted to share the modifications with you.

Some of the new control consist of:

slider-advanced:
d6bc0d90b9ef6d88cef435c5e07a0fbc

Which has the ability to select a unit without hard coding one suffix. This also has media queries (similar to elementor).

border:
border
Pretty self explanatory.

spacing-advanced:
spacing-advanced

Pretty much the same as spacing, but with the ability to sync all fields with media queries (similar to Elementor)

toggle tabs:
ezgif-5-a9e9cc8c27cd

For our project, we needed an ability to tab controls together. Now, I wasn't sure how to pull that off, BUT I did a little high-jacky method that pulls other controls list items and sticks them into its own while maintaining the original events. Its a little glitchy with requireds, but I haven't figured out a proper fix yet...

```
Kirki::add_field('theme-options', array(
	'label' => esc_html__('Button background', 'text-domain'),
	'section' => 'buttons_section',
	'settings' => 'btn_bg_tabs',
	'type' => 'toggle-tabs',
	'required' => array(
		array(
			'setting' => 'btn_style',
			'operator' => '==', 
			'value' => 'standard'
		)
	),
	'choices' => array(
		esc_html__('Normal') => array(
			'btn_bg_style',
			'btn_bg_classic',
			'btn_bg_gradient'
		),
		esc_html__('Hover') => array(
			'btn_bg_hover_style',
			'btn_bg_hover_classic',
			'btn_bg_hover_gradient'
		)
	),
	'transport' => 'auto'
));
```
An example of how its use.

typography-advanced:
typography

Pretty much the same as typography, but with media queries (Can be disabled).

box-shadow:
box shadow

Pretty self explanatory. I think you did add a box shadow control already, so this one is late to the party.

color-gradient:
gradient

A color gradient control.

sortable (mod):
sortable

I added a 'mode' to sortable which allows both show/hide along with custom text.

```
Kirki::add_field('theme-options', array(
	'label' => esc_html__('Social media icons', 'konio'),
	'section' => 'social_media_icons_section',
	'settings' => 'social_media_icons',
	'type' => 'sortable',
	'mode' => 'text',
	'choices' => array(
		'facebook' => esc_html__('Facebook', 'konio'),
		'twitter' => esc_html__('Twitter', 'konio'),
		'instagram' => esc_html__('Instagram', 'konio'),
		'snapchat' => esc_html__('Snapchat', 'konio'),
	),
	'default' => array(
		'facebook' => '#',
		'twitter' => '#',
		'email' => '#'
	)
));
```

I also added a new module for resetting a section inside of customizer. I saw in a post issue post that you removed it cause of stability issues, but I discovered a stable way to handle resetting.

reset

```
	/**
	 * Handles resetting called by reset button
	 */
	public function ajax_reset_section()
	{
		$section = isset ( $_REQUEST['section'] ) ? $_REQUEST['section'] : '';
		$nonce = isset ( $_REQUEST['nonce'] ) ? $_REQUEST['nonce'] : '';
		if ( !wp_verify_nonce( $nonce, 'kirki-section-reset'  ) )
			wp_send_json_error( __( 'Invalid nonce.', 'kirki' ) );
		if ( empty( $section ) )
			wp_send_json_error( __( 'Section not set', 'kirki' ) );
		
		if ( isset( Kirki::$sections[$section] ) )
		{
			foreach ( Kirki::$fields as $field )
			{
				if ( $field['section'] !== $section )
					continue;
				if ( $field['option_type'] === 'theme_mod' )
					remove_theme_mod( $field['settings'] );
				else
					delete_option( $field['settings'] );
			}
			Kirki::$skip_output_context = true;
			new Kirki_CSS_To_File();
			do_action( 'customize_save_after' );
			Kirki::$skip_output_context = false;
			
			update_option( '_kirki_customize_last_section', $section );
			
			wp_send_json_success();
		}
		else
		{
			wp_send_json_error( __( 'Could not find section', 'kirki' ) );
		}
	}
```

There are the controls and also internal mods like the dependency postMessage output issue, section reset, etc.

Like I mentioned before, I've been working on this changes for a while and wanted to bring them to your attention before things got out of hand or you decided to do a complete 180 with the project.

That way, these additions/changes can be included in the changes.

I'm a little cramped on time right now (And I may of forgotten some things), but let me know if you have any questions! And I'll be posting more examples later today.

I also merged this with your current commit.

This is also one of my first contributions to open-source projects, so let me know if some things are off.

P.S.

I made different controls (slider-advanced, typography-advanced, etc) to keep the integrity of the current controls.

Nathan

### CODE REVIEW

**Comment by aristath** [comment]
wow... this PR is epic/monstrous in size, it's gonna take me a while to review everything. :rofl: 
Thank you! I'll check the code later today after work :+1:

**Comment by ArekZw** [comment]
Wow! @CaptJiggly, thank you!

**Comment by aristath** [comment]
@CaptJiggly can you also add examples for your controls in the examples.php file?
It's an easy way for devs to see how everything works, have a reference for available options etc.
You should be able to just add `define( 'KIRKI_TEST', true );` and see a new panel with all available controls :+1: 
It would also make it easier for me to review and see what each control does rather than going through all code to see what arguments are available, what type of data they accept, create demo controls, see how they function, and then review the code that drives them :rofl:

**Comment by CaptJiggly** [comment]
@aristath Yeah, definitely. I have a separate file I was using for testing in our project, but let me merge them into example.php.

**Comment by CaptJiggly** [comment]
@aristath I added the controls to example.php. Also, thanks for that tip. I didn't notice that. It'll make testing controls easier in the future!

**Comment by CaptJiggly** [comment]
Another note. With the media queries in slider-advanced (etc), those can be controlled globally via Kirki::add_config.

```
	Kirki::add_config('theme_options_name', array(
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
		'media_queries' => array(
			'tablet'  => '@media screen and (max-width: 991px)',
			'mobile'  => '@media screen and (max-width: 767px)'
		)
	));
```

**Comment by CaptJiggly** [comment]
The metaboxes are... a hot mess right now to be honest. Like I was asking you before when thinking of a way to use the original templates and recreate the JS if needed.

That portion is not complete, so if you want to drop that from your develop branch, that's understandable. Or if you would like to collaborate and find the best approach, that would be even better!

**Comment by aristath** [comment]
I'll be honest... this PR is way too large to properly review, it's going to take me a while.

So far I've only reviewed the slider and I have to admit I don't quite get it.

First of all, I don't see the media queries anywhere, in any of your controls. 
But even if I did, I've been struggling for days with the idea and I don't understand why a developer would want to add media-queries in controls. Don't get me wrong, I get _why_ it's there, Elementor has it too in its elements and when building a page it's useful because typography is not responsive/adaptive. 
**But why not just make the typography adaptive?** Why do we work on workarounds instead of solving the underlying problem?
I guess that's just my naive and somewhat philosophical point of view, but I've always believed that these responsive controls in Elementor are a bad example and are only there to work around the limitations of the theme used in conjunction with Elementor. The plugin can be used with any theme so it has to be able to work well with all of them. So, the best solution in that case was to add media queries in font-sizes etc. It made sense for them. But why follow the same bad example when building a theme and one has the opportunity to build something really good without all these limitations?

Secondly, why save the value as an array? why `[value:20, unit:'px']` instead of plain `20px`? Would it not be simpler to implement and potentially cleaner?

**Comment by CaptJiggly** [comment]
I figured it would take a while.

The media queries can be enabled by adding:

'use_media_queries' => true

In say slider-advanced for example.

```
	'choices' => array(
		'use_media_queries' => true,
		'units' => array(
			'px' => array(
				'min' => 1,
				'max' => 500,
				'step' => 1
			),
			'em' => array(
				'min' => 1,
				'max' => 30,
				'step' => .1
			)
		),
	),
```

> Secondly, why save the value as an array? why [value:20, unit:'px'] instead of plain 20px? Would it not be simpler to implement and potentially cleaner?

Why I split them up is for reloading purposes.

Since we're allowing the user to also select multiple units as well (See example above), I needed to know which unit they selected to reload inside of customizer. Having it as one string would be cleaner output wise, yes, but parsing it back was iffy to me.

I originally had RegEx to parse, but decided to go with this. I'm still on the fence about it.

And about where the media queries are, some defaults are defined in `class-kirki-config.php`

```
		$default_queries = [
			'desktop' => 'global',
			'tablet' => '@media screen and (min-width: 768px) and (max-width: 991px)',
			'mobile' => '@media screen and (max-width: 575px)'
		];
		if ( !isset( $this->config_final['media_queries'] ) )
			$this->config_final['media_queries'] = array();
		foreach ( $default_queries as $k => $v )
		{
			if ( !isset( $this->config_final['media_queries'][$k] ) )
				$this->config_final['media_queries'][$k] = $v;
		}
```

The user/developer can change them when create a config however.

```
	Kirki::add_config('theme-options', array(
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
		'media_queries' => array(
			'tablet'  => 'custom media query'
			'mobile'  => 'custom media query'
		)
	));
```

Above was done so you do not have to copy and paste media queries everywhere. So all the advanced controls that utilize desktop/tablet/mobile buttons inherit the same values. I now realize I should make them override-able  per control, but I can add that later on.

**Comment by CaptJiggly** [comment]
@aristath Hey, ignore my pull request for now. I need to tweak some things in the controls that are broken and I'm also going to simplify some things and fix the code standard issues.

**Pull request closed without merging**
