### PR TITLE
Issue 831 - Repeater major changes

### PR DESCRIPTION
**Pull request by guillaumemolter**
- Major CSS & JS cleaning and refactoring
- Major UX/UI update (to offer something similar to Menu and Widgets)
- Dynamic Row Labels : user can now override the “row” text string as well as define a text input as label (i.e.:title)

Related to #831

### CODE REVIEW

**Comment by aristath** [comment]
looks good... 
Merged in develop. :+1: 

We can do more testing etc there. That's the branch most devs use, so if there's an issue we'll be able to catch it early on. 

Great work...

**Comment by Rayken** [comment]
Any documentation on how to change the labels? I'd like to be able to set the "Row #" as well as "Add new X" labels fully. Not just the "Row" if that makes any sense!

**Comment by guillaumemolter** [comment]
@Quaked updating the documentation is also on my to-do list :-) but you'll find some details here : #831

**Comment by guillaumemolter** [comment]
@Quaked feel free to submit a PR to the documentation with this ;-)

**Comment by Rayken** [comment]
@guillaumemolter point being I don't know. Right now I'm using a field to populate the "title", but I'm not aware of a way to change the actual text "Add new". This is what I've got and it works, but I still need to change the 'Add new' text:

``` php
Kirki::add_field( self::$cfg, array(
    'type'          => 'repeater',
    'label'         => esc_attr__( 'Sektioner', Settings::$textdomain ),
    'section'       => 'front_sections',
    'priority'      => 10,
    'settings'      => 'sections',
    'fields'        => $section_fields,
    // this replaces *row* in; "Add new row" and title "Row #" until replaced by field 'section_header'
    'row_label'     => array(
        'type'          => 'field',
        'value'         => 'section',
        'field'         => 'section_header',
    ),
));

```

**Comment by guillaumemolter** [comment]
Ok sorry I thought my comment in #837 was clear, obviously it is not.

So you currently have 3 options:
1. Don't pass the 'row_label' parameter. It will result in the repeater using the default value:
   `array( 'type' => 'text' , 'value' => 'row' )`
   **Result:** Each row will have a "Row X" label and the add button label will be "Add new row"
2. Change the text label by passing the `row_label` parameter with a value:
   `array( 'type' => 'text' , 'value' => 'slide' )` _N.B.: I'm pretty sure that type=text is not even required in this case_
   **Result:** Each row will have a "Slide X" label and the add button label will be "Add new slide"
3. Use dynamic field labels by passing the `row_label` parameter with a value:
   `array( 'type' => 'field' , 'value' => 'slide', 'field' => 'a-field-id' )`
   **Result:** As long as `a-field-id` is empty the row will have a "Slide X" label and will then switch to `a-field-id` value once not empty. The add button label will be "Add new slide".

Other use cases are currently not supported.

**Comment by Rayken** [comment]
Ah. I believe you were clear, just not in regards to the text **Add new** which unfortunately doesn't seem to be changeable. That's the issue really, my theme options aren't in English! As an example, 'row' is 'rad' in Swedish, so I'm getting "Add new rad". Maybe a future update will sort this out as some other parts (like 'Add Image' in the image field) aren't translatable either.

**Comment by guillaumemolter** [comment]
So you can definitly translate the "add new" as it is [added using `l10n` ](https://github.com/aristath/kirki/blob/develop/includes/controls/class-kirki-controls-repeater-control.php#L101-L103). The only current constraint is that "row/rad" has to be at the end of the label but it doesn't seem to be an issue in your case (Lägg till ny rad).

You'll have to ask @aristath for more details on how translation works in Kirki.

**Comment by aristath** [comment]
@Quaked You can translate those using poEdit just like any other WordPress plugin, or using the web-ui from https://translate.wordpress.org/projects/wp-plugins/kirki

Otherwise you can always do something like this:

``` php
function my_custom_translation_strings( $config ) {
    $config['i18n']['add-new'] = 'LALALA';
    return $config;
}
add_filter( 'kirki/config', 'my_custom_translation_strings' );
```

You can see the strings available for translation this way here: https://github.com/aristath/kirki/blob/2.3.0/includes/class-kirki-l10n.php#L101-L217

**Pull request merged**
