### PR TITLE
Get categories helper function

### PR DESCRIPTION
**Pull request by ragzor**
Added a helper function to get a list of available categories, useful when adding a select picker for categories

### CODE REVIEW

**Comment by aristath** [comment]
Hmmm....
I like the idea, but if we add a method to get categories, then we'll have to add another to to get tags, then another one to get custom taxonomy terms and so on.
Can you instead make this a bit more abstract?
So instead of `get_categories() { }`, something like `get_terms( $taxonomy = 'category' ) { }`

This way we'll also be able to use the same method for product-categories on WooCommerce etc :+1:

**Comment by aristath** [comment]
Oh, and also please don't submit PRs against the master branch. Instead, submit your PRs against the `develop` branch 'cause that's where all the development happens. :+1: 
I'm trying to keep the master branch to the latest stable release.

**Comment by aristath** [comment]
Closing this one so you can submit a new PR against `develop` :wink:

**Comment by ragzor** [comment]
Perfect! Thanks! 😁

**Pull request closed without merging**
