### PR TITLE
Remove Duplicate License URL

### PR DESCRIPTION
**Pull request by nfmohit**
Hi there! 👋 
Hope you are doing well! ❤️ 

This is rather a very simple pull request. I was just roaming around in the code and found a duplicate license URL in the telemetry implementation file. This PR just simply removes that.

Thank you ❤️

### CODE REVIEW

**Comment by aristath** [comment]
Thanks! merged :+1:

**Comment by nfmohit** [comment]
Thank you Ari ❤️

**Comment by aristath** [comment]
btw, in case you want to contribute more, the project is now split to separate composer modules which can be found on https://github.com/kirki-framework/ :wink: The separate packages will make maintenance, documentation and moving the project forward a lot easier.
I already ported this commit to the separate package there.

**Comment by nfmohit** [comment]
Right on spot! Duly noted and I'll check them out. Thanks, bud ❤️

**Pull request merged**
