### PR TITLE
Slider bug when no default values are set

### PR DESCRIPTION
**Pull request by ragzor**

### CODE REVIEW

**Comment by aristath** [comment]
I'm not really sure about this one...
When a user adds a slider, they are _required_ to add the necessary arguments.
I have no objection adding some sane defaults, but why 0-100 with a step of 1?
Why not 0-1 with a step of 0.01 ?
Why not something else?
Could you please explain your reasoning?

**Comment by ragzor** [comment]
hey! @aristath wanted to quickly test an option using slider control with it's default values however got `Uncaught SyntaxError: Unexpected token ,`.

also I chose those values because they were _Jquery-ui-slider_ defaults

**Comment by sherbrow** [comment]
Since jquery-ui has defaults and doesn't require those arguments ([Slider doc](http://api.jqueryui.com/slider/#option-max)), there has to be either a default hardocded value or the option of not setting those arguments

```
<?php if($this->choices['min'] != '') { echo 'min: ' . $this->choices['min'] . ','; ?>
```

**Comment by aristath** [comment]
OK, I'm convinced.
Merging. :+1: 

Thanks @ragzor and @sherbrow for your input. :smile:

**Pull request merged**
