### PR TITLE
Allow postMessage for :before, :after, :hover selectors

### PR DESCRIPTION
**Pull request by luanvuvt**
Currently we can not use postMessage for selectors which contain :before, :after, :hover, for example a:hover. This problem causes the customizer is hard to see change immediately.
I have did some changes to fix it. Please take a look at this PR.

### CODE REVIEW

**Comment by aristath** [comment]
It looks like there's something wrong and your code doesn't pass the phpunit tests.
To be more specific, this is the test that fails: https://github.com/aristath/kirki/blob/master/tests/test-kirki-scripts-customizer-postmessage.php#L26-L29
It should be returning the string containing the script and instead it's getting an array as seen on https://travis-ci.org/aristath/kirki/jobs/74279212#L352

I see you changed the names of some functions etc...
Could you please include a fix for the unit tests in your PR as well?

**Comment by luanvuvt** [comment]
Hi @aristath,
Thanks for your reply!
Because I have to insert JavaScript and CSS in the footer, so I returned a array. Maybe we should rewrite the unit test to work with new change :)
Please take a look at it here: https://github.com/luanvuvt/kirki/commit/427e1850ce52926e6227d83f53793f9049fd0381#diff-0fc4d00a4dd8a0ad9a9a9cb4e32119caR76

**Comment by aristath** [comment]
@luanvu I've been going through all the PRs and issues and I saw this one again...
I'm sorry, I completely forgot about this!

Could you please update the PR so it doesn't conflict with the latest changes we made to the repo so that we may merge it?

Thanks!

**Comment by luanvuvt** [comment]
Hi @aristath, I have just updated the PR to fix conflict. Please recheck it.

**Comment by luanvuvt** [comment]
Hi @aristath,
Could you please check this PR?
Thanks!

**Comment by aristath** [comment]
The reason I haven't merged this yet is because I'm trying to understand what you're doing, and something just doesn't seem right.
Example:
on this line: https://github.com/aristath/kirki/pull/289/files#diff-8abb598b6325e38c3fb671fb128b0c2bR256 and line 264 just below that, it's clear that the new `generate_css_by_fields` method acceps ALL fields as the 1st argument.
However, when you call that function on https://github.com/aristath/kirki/pull/289/files#diff-0fc4d00a4dd8a0ad9a9a9cb4e32119caR47 and on line 67 on the `class-kirki-scripts-customizer-postmessage.php` file, you're sending a single field instead.

I mean... if all we want to do is allow using pseudo-elements, wouldn't we be able to do it by tweaking these lines https://github.com/aristath/kirki/blob/67b81801028e9b423bd5f4b46d5808be810e6f21/includes/class-kirki-scripts-customizer-postmessage.php#L49-L51 ?
We should be able to just check if we have a `:` character in the `$js_vars['element']`, and if we do then use jquery's `.attr`. Or am I missing something obvious?

I'm not that good when it comes to JS so I don't have the whole picture, it just seems like overkill.
If I'm mistaken then please do correct me, it's how we learn.

**Comment by luanvuvt** [comment]
Hi @aristath,
In this PR, I don't use jquery's .attr to change style of element. Intead of this I use a style element. Please take a look at simple example here for more details http://jsbin.com/wumaramumi/1/edit?html,output
About the new method generate_css_by_fields, because there are some places I have to generate CSS by a field, so I make a small change in this method to allow to generate CSS of array of fields or a field only.
Hope this useful!

**Comment by aristath** [comment]
There were lots of issues, in fact the output stopped working altogether when in the customizer so I had to revert this merge.

**Comment by luanvuvt** [comment]
Yes. We have tested this change in our themes but we don't see any problem. Maybe it does not fit to general case.

**Pull request merged**
