### PR TITLE
Field type editor css fix

### PR DESCRIPTION
**Pull request by rinkuyadav999**

### CODE REVIEW

**Comment by aristath** [comment]
Hey there!

Any reason why these changes are not included directly in https://github.com/aristath/kirki/blob/develop/controls/editor/editor.scss ?

**Comment by rinkuyadav999** [comment]
Hi @aristath 

I have tested develop branch and editor button does not open editor so difficult to test for me. i have kirki version 2.3.7 and i implement this change and worked fine.

let me know what i have to do to implement in latest version.

Thanks

**Comment by aristath** [comment]
I just noticed that you're working on the master branch...
Have you tried the develop branch?
Perhaps this was already fixed there?

**Comment by rinkuyadav999** [comment]
Yes I have tried develop branch and button to open editor do not open editor.

**Comment by rinkuyadav999** [comment]
Today I tested version 2.4.0-beta.1 again and button to open editor do not display properly and also it does not open editor to write content.
field-editor-issue-in-2 4 0-beta 1

**Comment by rinkuyadav999** [comment]
I am expecting, you will merge this PR in 2.3.7 and upload on w.org so we can enjoy field type editor perfectly. and hoping it will be not an issue in 2.4.0.

**Comment by aristath** [comment]
I can't merge this because a lot of things have changed in the plugin's structure since 2.3.7 and this can no longer be merged in the develop branch.
However I applied the same changes in 2.4.0 (develop branch) so I'm closing this one.

**Pull request closed without merging**
