### PR TITLE
Feature/oop

### PR DESCRIPTION
**Pull request by vpratfr**
A starting point for #109

### CODE REVIEW

**Comment by vpratfr** [comment]
Next step would be to reorganize the folder structure within includes to make it compliant with PSR4/0 standard:
- Put all our classes into a structured namespace
- Each class name should not be prefixed by "Kirki_"
- Name each file just like the class name (eg. class-kirki-control.php -> Control.php)
- ...

For that, you would need to abandon PHP 5.2 compatibility (which in my opinion is the most absurd WordPress requirement and which is quickly being abandonned by all plugin/theme authors wanting at least PHP 5.3)

**Comment by aristath** [comment]
I don't really care for 5.2 compatibility... If you notice in the composer.json file that you submitted 3 days I immediately changed the minimum php version to 5.3
So yeah... feel free to drop it. :)

To be honest though, I don't know much about PSR and the tools that you use.
I've started studying, but I won't be as fast as you (obviously).

Any useful tutorials/resources you can recommend so that I may improve my skills on this area?
In the meantime feel free to submit additional commits on this PR and I'll merge everything once it's finished.

**Comment by vpratfr** [comment]
You can safely merge this one. I'll create more branches for other refactoring. 

This will be easier for me as I won't have too many conflicts to solve while you continue working on the rest.

This PR should be pretty safe. I did not change much.

**Comment by vpratfr** [comment]
Some doc for you: http://culttt.com/2014/05/07/create-psr-4-php-package/

Don't worry, once I have reorganised your code this will look pretty clear.

**Comment by aristath** [comment]
OK.

I'm currently getting a `Fatal error: Class 'WP_Customize_Control' not found in /srv/www/wordpress-trunk/wp-content/plugins/kirki/includes/controls/class-kirki-customize-group-title-control.php on line 3` though using this branch...
Once that's fixed I'll merge. :wink:

**Comment by vpratfr** [comment]
Oh. I guess that's why you have the control includes inside a hook running after customizer setup right? I had moved those includes with all the others.

**Comment by aristath** [comment]
Yeah,  it's a minor nuisance loading them like that but necessary.

**Comment by vpratfr** [comment]
Should be fine now

**Comment by aristath** [comment]
:+1:

**Pull request merged**
