### PR TITLE
Using active_callback Inside Repeater Controls

### PR DESCRIPTION
**Pull request by Oxibug**
Hi @aristath,
I made a solution to enable the [active_callback] in repeaters controls and hope to add it as soon as you can.

And here's a complete tested example

```

Kirki::add_field( KIRKI_CONFIG_PREFIX, array(
    'type'        => 'repeater',
    'settings'     => '_builder_repeater',
    'label'       => esc_html__('Builder', 'text-domain'),
    'description' => '',
    'help'        => '',
    'section'     => 'section_id',
    'default'     => '',
    'priority'    => 10,

    'row_label' => array(
        'type'  => 'field',
        'value' => esc_html__('Layout', 'text-domain' ),
        'field' => 'layout',
    ),

    'default'     => array(),

    'fields' => array(
        'layout' => array(
            'type'        => 'select',
            'label'       => esc_html__( 'The Box Layout', 'text-domain' ),
            'description' => '',
            'default'     => 'classic',
            'choices'       => array(
                'classic'   => esc_html__( 'Classic', 'text-domain' ),
                'horizontal'     => esc_html__( 'Horizontal', 'text-domain' ),
                'vertical'      => esc_html__( 'Vertical', 'text-domain' ),
                'review'       => esc_html__( 'Best Reviews', 'text-domain' ),
            )
        ),

        'title' => array(
            'type'        => 'text',
            'label'       => esc_html__( 'Title', 'text-domain' ),
            'description' => '',
            'default'     => '',
        ),

        'category' => array(
            'type'        => 'select',
            'label'       => esc_html__( 'Category', 'text-domain' ),
            'description' => '',
            'default'     => 'img',
            'choices'       => array(
                'img'   => esc_html__( 'Images', 'text-domain' ),
                'video'     => esc_html__( 'Video', 'text-domain' ),
                'audio'      => esc_html__( 'Audio', 'text-domain' ),
            ),
        ),

        'title_2' => array(
            'type'        => 'text',
            'label'       => esc_html__( 'Title #2', 'text-domain' ),
            'description' => '',
            'default'     => '',
            'active_callback'      => array(
                array(
                    'setting'  => 'layout',
                    'operator' => '==',
                    'value'    => 'vertical',
                ),
                array(
                    'setting'  => 'category',
                    'operator' => '==',
                    'value'    => 'video',
                )
            )
        ),
        'cat_2' => array(
            'type'        => 'select',
            'label'       => esc_html__( 'Category #2', 'text-domain' ),
            'description' => '',
            'default'     => 'animal',
            'choices'       => array(
                'animal'   => esc_html__( 'Animals', 'text-domain' ),
                'flys'     => esc_html__( 'Flys', 'text-domain' ),
            ),
            'active_callback'      => array(
                array(
                    'setting'  => 'layout',
                    'operator' => '==',
                    'value'    => 'vertical',
                )
            )
        ),


        'rev_title' => array(
            'type'        => 'text',
            'label'       => esc_html__( 'Review Title', 'text-domain' ),
            'description' => '',
            'default'     => '',
            'active_callback'      => array(
                array(
                    'setting'  => 'layout',
                    'operator' => '==',
                    'value'    => 'review',
                )
            )
        ),

    )

) );
```

### CODE REVIEW

**Comment by ravishakya** [comment]
When will this be merged?

**Comment by chandra-deb** [comment]
Why this code isn't merged? @Oxibug

**Comment by dedalx** [comment]
Same question, when this will be added to release? We are waiting for this for 3 years.

**Comment by dedalx** [comment]
This change still have some issues:
1) Select elements with multiselect option renders incorrectly (does not allow to search within Select2() library for entries). Looks like changes break select2.
2) If you selected item that should display something, while customizer is loading for new content, and you select item that should hide option while customizer is still loading - option remain visible. This works properly only if you change options AFTER customizer is fully loaded page.

**Comment by Oxibug** [comment]
@ravishakya @chandra-deb @dedalx 
Hey Guys, I think @aristath will build the repeater from scratch in version 3.1 But I need it urgently so I decide to fix it now until version 3.1 released.

@dedalx 
1. I noticed  that multiple repeaters not working together so I upload the new commit right now.
2. For multiselect I think the repeater doesn't support it.
3. I noticed that the page doesn't listening for new values while reloading sometimes before this fixes, It happened with me a lot and I don't know the reason so far.

Like  said you can make your own Kirki with version 9.0.0 for example to stop updating until Aristath commit these changes or build it from scratch.

Thanks

**Comment by aristath** [comment]
I haven't been actively involved in Kirki in more than a year... Please read https://wptavern.com/david-vongries-takes-over-as-new-owner-of-the-kirki-customizer-framework and more recently https://twitter.com/MapSteps/status/1374278880895365120. Replying to that tweet might be the best way to see what can be done.

**Comment by Oxibug** [comment]
@ravishakya @chandra-deb @dedalx 
Hey Guys, 

A new commit to enable active_callback in the newer version 4.x.x is available here https://github.com/kirki-framework/kirki/pull/2468

Like I said you can make your own Kirki with version 9.0.0 for example to stop updating until commit these changes in the master.

Best,
Hady Shaltout

**Comment by Braintheme** [comment]
Hi, it's still don't working.

**Comment by Oxibug** [comment]
> Hi, it's still don't working.

The current PR is for v3.x, This PR https://github.com/kirki-framework/kirki/pull/2468 for Kirki v4.x

**Pull request closed without merging**
