### PR TITLE
Adding color picker field to the repeater field

### PR DESCRIPTION
**Pull request by guillaumemolter**
Closing #901

### CODE REVIEW

**Comment by Rayken** [comment]
@guillaumemolter Is efe1d6f working in the current release? I get the 'div' for it but it's empty using:

``` php
    'type'        => 'color',
    'label'       => __( 'Bakgrundsfärg', Settings::$textdomain ),
    'default'     => '#0088CC',
    'priority'    => 60,
```

Something about e9d498a (https://travis-ci.org/aristath/kirki/builds/123559294) failing?

**Comment by guillaumemolter** [comment]
I think @aristath only merged it on the dev branch, it will probably be released with [2.3.1](https://github.com/aristath/kirki/pull/870)

**Comment by aristath** [comment]
> I think @aristath only merged it on the dev branch, it will probably be released with 2.3.1

Correct.
2.3.1 will be released shortly.

**Comment by Rayken** [comment]
Nice! Will 'editor' also work with repeater fields in that version?

**Comment by aristath** [comment]
> Nice! Will 'editor' also work with repeater fields in that version?

no, not yet.
editor fields are currently pretty troublesome.

**Comment by Rayken** [comment]
@guillaumemolter @aristath
So I just updated to try this one out but I'm just getting a regular text field although it has the placeholder text "HEX color" but it doesn't trigger the color picker - is this intentional? Something wrong with how I set it up (as above) maybe?

Thanks for pushing updates to this amazing plugin and working with the repeater field!

EDIT: so now it works, I removed the theme mods and "re-initialized" the field and it works. Not sure what happened there. Works perfectly!

**Comment by Rayken** [comment]
@guillaumemolter I tried adding 'alpha' => true but I'm not getting it to function. The color picker shows up but there's no alpha to it. Might be related to the comment above but I figured I'd ask anyway as I can imagine it's meant to function with repeater fields as well?

**Comment by guillaumemolter** [comment]
Yeah alpha is not supported yet. I'm using the native WP Color Picker and I don't think it supports alpha out of the box.

**Comment by Rayken** [comment]
All right, that makes sense - thought I was doing it wrong. Thanks for the reply @guillaumemolter

**Pull request merged**
