### PR TITLE
Use class instead of data-id selector in controls

### PR DESCRIPTION
**Pull request by dennisnissle**
Fixes issue #2077. Uses class `kirki-data-holder` to select inputs within it's control. This change enables developers to dynamically add controls and settings to the customizer without losing access to the selector which was selected via data-id attribute.

### CODE REVIEW

**Comment by aristath** [comment]
I'm still a bit torn about this one and how to implement it.

The problem is not with what you're doing here, I get that and what you want to do is fine. But as I mentioned in the ticket, `data-id` was added because I'm slowly refactoring things to allow repeaters to be containers of controls instead of containers of `<input>` fields (I hope that sentense makes sense).
So right now there's a `kirki.input` object, a `kirki.control` object, some views etc. The data-id works the way it does because of this hypothetical future scenario:
A user uses options instead of theme-mods (don't ask me why, people are just weird sometimes).
Then they have a repeater.
Inside the repeater, there's a `background` control.
Background controls save values as an array like this:
```php
[
	'background-color' => '#ffffff',
	'background-image' => 'https://domain.com/foo.png',
]
```

In the above scenario, `data-id` for the background color setting inside the background control inside an item in the repeater would look like this:
```
mysetting[my-repeater][0][my-background-control][background-color]
```
So there's the `kirki.setting` object that reads the `data-id` and sets the values. The `kirki.setting.set` method understands settings formatted like the one above and t will check the following:
1. Does the `mysetting[my-repeater][0][my-background-control][background-color]` exist in the customizer? No. I need to go back a level.
2. Does the `mysetting[my-repeater][0][my-background-control]` exist in the customizer? No. I need to go back a level.
3. Does the `mysetting[my-repeater][0]` exist in the customizer? No. I need to go back a level.
4. Does the `mysetting[my-repeater]` exist in the customizer? YES! Found it!
5. remove `mysetting[my-repeater]` from `mysetting[my-repeater][0][my-background-control][background-color]` and see what I'm left with.
6.  I've got `[0][my-background-control][background-color]` so I need to save this:
```php
0 => [
	'my-background-control' => [
		'background-color' => '#ffffff',
	]
]
```

So.... with the above in mind, how would this PR work?

**Comment by dennisnissle** [comment]
Hi there,

thanks for the feedback. I get the problem. Did you already test your implementation? I guess the repeater option implies that elements are dynamically added to the DOM? E.g. when adding a new field within the repeater? That would create the same problem that I experienced with the data-id attribute as the controls within the new repeater field won't be initialized correctly. 

Also I do not 100% get how the data-id attribute related to the initialization of the control? Is that really necessary? All I've changed within the PR is the way controls are selected for initialization - you may add the class `kirki-data-holder` (or whatever you might name it) to your repeater items (which I guess does only clone/copy markup) as well. 

It is hard for me to understand what you are after without having a look at the actual implementation that's why maybe I'm getting it wrong :)

Cheers,
Dennis

**Comment by aristath** [comment]
> It is hard for me to understand what you are after without having a look at the actual implementation that's why maybe I'm getting it wrong :)

Yeah, it's hard for me to explain it too... So far it's not implemented or tested anywhere, it's all just in my head brewing and mentally debugging.

I've merged this PR, we'll debug the repeater when everything else is finished and there's an actual implementation to test against.

**Comment by aristath** [comment]
@vendidero I'm afraid I had to revert this.

The problem is the use of `control.container.find( 'input.kirki-data-holder' );`
We can't rely on the `control` object... 
Forget about repeaters. Think of a very simpler scenario: a `background` control, or even a `typography` control.
The typography control for example right now is a separate control, but once the migration is finished it will simply be a collection of select controls, checkboxes etc.
If we use `control.container.find( 'input.kirki-data-holder' );` on the select, then it won't be able to properly detect the option.

Perhaps I could take a look at your theme and what it is you're trying to accomplish so we can come up with a solution together?

**Comment by dennisnissle** [comment]
Hi @aristath,

ok - this is the JS (excerpt) I'm currently using to "clone" existing settings/controls:

```javascript
// Get the existing "placeholder" section and clone it
var newSectionParams      = $.extend( {}, section.params );
newSectionParams.id 	  = newBaseId;
newSectionParams.priority = 170;

var newSection 			  = new builder.vars.api.Section( newSectionParams.id, newSectionParams );

builder.vars.api.section.add( newSection );

// Add section to builder
builder.sections[ newSection.id ] = newSection;

// Register settings + controls by looping through existing settings and cloning them
$.each( elementType.settings, function( i, setting ) {
	var settingId		  = section.id + '_' + setting.id,
		customizerSetting = customizerSettings[ settingId ],
		newSettingId	  = newBaseId + '_' + setting.id,
		newSettingValue   = customizerSetting.value;
        
         // Register the setting
	var newSetting = new builder.vars.api.Setting( newSettingId, newSettingValue, {
		transport : customizerSetting.transport,
		type      : customizerSetting.type,
		previewer : builder.vars.api.previewer,
		dirty     : true
	});

	builder.vars.api.add( newSetting );

	// Send the setting to the preview to ensure it exists there.
	newSetting.previewer.send( 'setting', [ newSetting.id, newSetting() ] );

	// Add controls
	var control 		 = builder.vars.api.control( settingId ),
		newControlParams = $.extend( {}, control.params );

	newControlParams.id 			  = newSettingId;
	newControlParams.section  		  = newSection.params.id;
	newControlParams.content		  = null;
	newControlParams.settings		  = $.extend( {}, newControlParams.settings );
	newControlParams.settings.default = newSettingId;
	newControlParams.instanceNumber   = null;
	newControlParams.link			  = null;

	var Constructor = builder.vars.api.controlConstructor[ newControlParams.type ] || builder.vars.api.Control, options;
	options 		= _.extend( { params: newControlParams }, newControlParams ); // Inclusion of params alias is for back-compat for custom controls that expect to augment this property.
	var newControl  = new Constructor( newControlParams.id, options );

	builder.vars.api.control.add( newControl );
});
```

What I'm currently trying to do is clone existing sections/controls and add them to the customizer. The problem is, that the Kirki inputs won't fire the change events and won't detect any changes made to the cloned inputs (due to the usage of data-id). I hope this helps you to understand my problem :)

Cheers

**Comment by aristath** [comment]
Do you have a theme you could send me so I can see this in action later today? 
Code is fine in most cases, but for more complicated issues like this one having something I can just install locally and play with is a lot more efficient 😊
You can find my mail on my GitHub profile

**Comment by aristath** [comment]
@vendidero the dev branch is not stable right now for production use, but it's stable enough to check if this one has been fixed already... I'm getting rid of the previous custom implementation and I'll be working on an alternate approach using the native customizer API. Now that WP has JS hooks it will be possible to handle the things that I was previously unable to do.

**Pull request merged**
