### PR TITLE
Add a composer file

### PR DESCRIPTION
**Pull request by vpratfr**
This would allow theme developers to pull the library as a composer dependency.

I have left some details blank in the author sections.

### CODE REVIEW

**Comment by aristath** [comment]
awesome, thanks! :+1:

**Comment by vpratfr** [comment]
You can then publish it on https://packagist.org/

So that we don't have to add the repository manually.

**Comment by vpratfr** [comment]
@aristath forgot to ping you about that

**Comment by aristath** [comment]
done. :)

**Pull request merged**
