### PR TITLE
0.8

### PR DESCRIPTION
**Pull request by aristath**

### CODE REVIEW

**Comment by vpratfr** [comment]
Lots of commits here have nothing to do with OOP, I think you should merge regularly to develop and not let things accumulate in PRs. 

When a PR is tested, just merge to develop. We'll make new PRs when new commits are done on this topic.

PS: I don't think you should keep deprecated classes around. Let it die, you are not maintaining the whole WordPress project and rather targetting developers who will be able to make the switch. That's just asking for bug reports and maintainance nightmare.

**Comment by aristath** [comment]
@vpratfr I do merge in the develop branch regularly...
This is a PR from the develop branch to the master branch. It's just mis-labeled as **OOP re-design**

I'll just change its title to 0.8 :)

**Comment by aristath** [comment]
I want to keep the deprecated classes just for a couple of months...
A few devs are using this on commercial projects so I have to give their clients time to update or their sites will break.

After a while we can safely remove them. If they don't update during that time it's their fault.

**Comment by aristath** [comment]
@vpratfr What other improvements do you think should be made from an OOP perspective?
I can start working on them...

**Comment by vpratfr** [comment]
Hi,

sorry, been really busy with my main WordPress project (http://wp-customerarea.com if you're looking for a good private area plugin for WordPress)

As you have probably noticed, I have started moving and renaming things. That's a first step towards autoloading heaven.

Basically : 
- each class in its own file
- set a namespace on top of the file
- name the class without any prefix
- file name should be same as the class name
- folder hierarchy should reflect the namespace structure

You can see what I mean with the controls for instance.

That would be a good first move.

**Comment by vpratfr** [comment]
**Second phase** of OOP : currently you don't really use OOP, you are simply wrapping methods within classes more or less.

There needs to be a proper design behind all those objects. That's what I started to introduce with the main Kirki class, the registries, ...

**Third are needing improvement** : the controls, they don't really take advantage of inheritance from their base class \WP_Customizer_Control. 

I believe that we should make all controls inherit in some sort of "wrapper" class around the real native customizer controls. Just like someone else does with his `SilverWP` library (saw the name on the issue or PR board not long ago)

**Comment by aristath** [comment]
ok, I'll start working on the file-naming and namespaces then. :+1:

**Pull request merged**
