### PR TITLE
compatibility with PHP 5.2

### PR DESCRIPTION
**Pull request by aristath**

### CODE REVIEW

**Comment by afzaalpersonal** [comment]
Awesome! Is Kirki now fully compatible with 5.2? Fast work! :+1:

**Comment by aristath** [comment]
Yup, it now works 100%.

Needs some improvement 'cause the file structure is not what it should be, but other than that it works 100%. :+1:

**Comment by vpratfr** [comment]
Wow, backwards move :/ 

Non-sense: 5.3 is the oldest PHP version that makes sense today. Even some numbers from WordPress core indicated that PHP 5.2 was on a small percentage of websites. 

And because WordPress requirement is 5.2 does not mean you should encourage that.

**Comment by dovy** [comment]
WTG @aristath   :)

**Comment by dovy** [comment]
@vpratfr The moment WP changes it's version, 5.3 will go right back. We kept it on a branch for that purpose. We just want to comply with .org submission requirements.

**Comment by aristath** [comment]
@vpratfr Yeah, I agree...
However wordpress.org announced yesterday that all themes on .org will HAVE TO use the customizer and not an options framework.
As a result, a lot of people asked for 5.2 compatibility so that their themes can include Kirki and be accepted on .org without any issues.

I agree, it was pretty lame and I think php 5.2 sucks and should be banned by law.
But this is a necessary evil for now so that people can use it. :disappointed:

**Comment by aristath** [comment]
This plugin just de-evolved and I hate that, but hopefully it's for the greater good and will help its adoption.

**Pull request merged**
